Algoritmo "semnome"

Var
   f, i: Real
Inicio
      Escreval ("Contagem inteligente")
      Escreval ("Inicio")
      Leia (i)
      Escreval ("Fim")
      Leia (f)
      se (i > f) entao
      Enquanto (i > f) faca
      Escreva (i)
      i <- i-1
      fimenquanto
      fimse
      se (i < f) entao
      Enquanto (i < f) faca
      Escreva (i)
      i <- i+1
      fimenquanto
      fimse
Fimalgoritmo
